title: Amna Mazen
description: Assistant Professor at Michigan Technological University 

joint appointment between the Department of Applied Computing and the Department of Manufacturing and Mechanical Engineering Technology
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
