title: Amna Mazen
logo: /Assets/images/Amna-Mazen-modified-smaller1.png
description: Assistant Professor at Michigan Technological University
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
